# Generated by Django 2.0.3 on 2018-03-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=50)),
                ('pos_x', models.FloatField(default=0.0, max_length=15)),
                ('pos_y', models.FloatField(default=0.0, max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
